# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: resque-state 1.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "resque-state".freeze
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Aaron Quint".freeze, "Nathan V".freeze]
  s.date = "2017-08-02"
  s.description = "resque-state is an extension to the resque queue system that provides simple trackable jobs. It provides a Resque::Plugins::State::Hash class which can set/get the statuses of jobs and a Resque::Plugins::State class that, when included, provides easily trackable/killable/pausable jobs.".freeze
  s.email = "nathan.v@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "examples/sleep_job.rb",
    "init.rb",
    "lib/resque-state.rb",
    "lib/resque/job_with_state.rb",
    "lib/resque/plugins/state.rb",
    "lib/resque/plugins/state/hash.rb",
    "lib/resque/server/views/state.erb",
    "lib/resque/server/views/state_styles.erb",
    "lib/resque/server/views/statuses.erb",
    "lib/resque/state.rb",
    "lib/resque/state_server.rb",
    "resque-state.gemspec",
    "test/test_helper.rb",
    "test/test_resque_plugins_state.rb",
    "test/test_resque_plugins_state_hash.rb"
  ]
  s.homepage = "http://github.com/nathan-v/resque-state".freeze
  s.licenses = ["MIT".freeze]
  s.rubyforge_project = "nathan-v".freeze
  s.rubygems_version = "2.6.11".freeze
  s.summary = "resque-state is an extension to the resque queue system that provides simple trackable jobs.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>.freeze, ["~> 1.27"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    else
      s.add_dependency(%q<resque>.freeze, ["~> 1.27"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    end
  else
    s.add_dependency(%q<resque>.freeze, ["~> 1.27"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
  end
end

